spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: asa-first-app

eureka:
  client:
    enabled: true
    serviceUrl:
      registerWithEureka: true

server:
  port: 8080