app:
  message1: "This is CC message 1 after main update"
  message2: "This is CC message 2"

spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: asa-second-app

eureka:
  client:
    enabled: true
    serviceUrl:
      registerWithEureka: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: *